// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aazmvlydygiquhlpcvkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhem12bHlkeWdpcXVobHBjdmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTA1MzMsImV4cCI6MjA1OTA4NjUzM30.I6ct97Cj4Y5TG90Jo95u3FqOArZv7Wtrz2g00USMc18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);